PREFIX rdfs: <http://www.w3.org/2000/01/rdf-schema#>

SELECT DISTINCT ?resource
WHERE {
    ?resource a <http://dbpedia.org/ontology/Film>;
                rdfs:label ?name

    FILTER regex(?name, ?regex, "i")
}