PREFIX ms: <http://mediaselector.com/data/ont/>

SELECT DISTINCT ?resource
WHERE {
    [] ms:like ?resource .

    ?user a ms:user;
          ms:has_id ?user_id .

    ?media a ms:media;
           ms:has_id ?media_id;
           ms:has_main_resource ?main_resource .

    ?resource a ?main_resource

    OPTIONAL {
        ?user ms:like ?liked_resource .
        FILTER (?liked_resource = ?resource)
    }
    FILTER (!BOUND(?liked_resource))
}