PREFIX ms: <http://mediaselector.com/data/ont/>

SELECT
?media_id
?media_name
?media_description
?media_end_point
(COUNT(?any_user) AS ?subscribed_count)
WHERE {
    ?media a ms:media;
           ms:has_id ?media_id;
           ms:has_end_point ?media_end_point;
           ms:has_name ?media_name;
           ms:has_description ?media_description;
           ms:has_author ?author .

    ?author ms:has_id ?user_id .

    OPTIONAL {
        ?media ms:has_subscribed ?any_user
    }
}
GROUP BY ?media_id ?media_name ?media_description ?media_end_point
ORDER BY DESC(?subscribed_count)